version: 2

jobs:
  pack:
    docker:
      - image: circleci/python:2
    steps:
      - checkout
      - run:
          name: Website Pack
          working_directory: slides
          command: |
            mkdir output/
            pip install -r requirements.txt --user
            ./build.sh once
            cp *.html output/
            cp *.css output/
            cp *.js output/
            cp -r images/ output/
      - persist_to_workspace:
          root: slides/output/
          paths: 
            - "*.html"
            - "*.css"
            - "*.js"
            - "images/"

  gh-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: output/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@omerlh"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "93:b2:24:5c:36:a1:81:14:b3:2f:49:31:62:aa:7d:5e"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --message "[skip ci] Updates" --dist output/
workflows:
  version: 2
  build:
    jobs:
      - pack
      - gh-deploy:
          requires:
            - pack
          filters:
            branches:
              only: master